// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz7RGkLFNEWJFUndQlcvWNUev7zNN1R4A',
    appId: '1:673137877402:web:8ec24df4fbc2f2a90a9a23',
    messagingSenderId: '673137877402',
    projectId: 'tortilleria-fd4d8',
    authDomain: 'tortilleria-fd4d8.firebaseapp.com',
    storageBucket: 'tortilleria-fd4d8.firebasestorage.app',
    measurementId: 'G-VTNCK916HW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8f7D_QhswLqPTEhR33XHtrwijLJJKHOg',
    appId: '1:673137877402:android:d1555e7c660672440a9a23',
    messagingSenderId: '673137877402',
    projectId: 'tortilleria-fd4d8',
    storageBucket: 'tortilleria-fd4d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT1YwWifs7YzgaRR1lZQvgYNr_sHJUMxs',
    appId: '1:673137877402:ios:44c4dcc994504f690a9a23',
    messagingSenderId: '673137877402',
    projectId: 'tortilleria-fd4d8',
    storageBucket: 'tortilleria-fd4d8.firebasestorage.app',
    iosBundleId: 'com.example.tortilleria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT1YwWifs7YzgaRR1lZQvgYNr_sHJUMxs',
    appId: '1:673137877402:ios:44c4dcc994504f690a9a23',
    messagingSenderId: '673137877402',
    projectId: 'tortilleria-fd4d8',
    storageBucket: 'tortilleria-fd4d8.firebasestorage.app',
    iosBundleId: 'com.example.tortilleria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz7RGkLFNEWJFUndQlcvWNUev7zNN1R4A',
    appId: '1:673137877402:web:1cb3fdfcd2325ae60a9a23',
    messagingSenderId: '673137877402',
    projectId: 'tortilleria-fd4d8',
    authDomain: 'tortilleria-fd4d8.firebaseapp.com',
    storageBucket: 'tortilleria-fd4d8.firebasestorage.app',
    measurementId: 'G-B0P47LGWVW',
  );
}
